### PR TITLE
german translation review

### PR DESCRIPTION
**Pull request by Art4**
Two typos fixed.

### CODE REVIEW

**Comment by Art4** [comment]
Will this ever be merged?

**Comment by Art4** [comment]
These are the changes from my branch `patch-1`, so you can add it if you have time in future. I'm going to delete my fork.

```diff
-  label_people_settings: Miterbeiter Einstellungen
+  label_people_settings: Mitarbeiter Einstellungen
```

```diff
-  label_people_background: Weiter Informationen
+  label_people_background: Weitere Informationen
```

Good luck and thank you.

**Comment by sergeyz** [comment]
Hi, @Art4!

Please pay attention to organization info
```
This is an automatically updated unofficial mirror of the RedmineCRM (http://redminecrm.com/) plugins
```

Will not be merged because next release will override files
Try to contact developers using form http://www.redminecrm.com/tickets/new or forum http://www.redminecrm.com/questions

**Comment by Art4** [comment]
Oh, good to know. Thank you.

**Pull request closed without merging**
